set(BUILD_SHARED_LIBS OFF)
set(BUILD_STATIC_LIBS ON)

set(CMAKE_POLICY_DEFAULT_CMP0077 "NEW")
set(CMAKE_POLICY_DEFAULT_CMP0154 "NEW")

set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_STANDARD 23)

set(CMAKE_SKIP_INSTALL_ALL_DEPENDENCY TRUE)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
